apiVersion: v1
kind: Secret
metadata:
  name: csi-secret
type: Opaque
data:
  adminID: {{ .Values.auth.id | b64enc }}
  adminKey: {{ .Values.auth.key | b64enc }}
  userID: {{ .Values.auth.id | b64enc }}
  userKey: {{ .Values.auth.key | b64enc }}
  