{{- range .Values.fs }}
apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: {{ .name }}
provisioner: cephfs.csi.ceph.com
parameters:
  clusterID: {{ $.Values.auth.clusterId }}
  fsName: {{ .fsName }}
  {{ template "secret" $ }}
reclaimPolicy: Delete
allowVolumeExpansion: true
mountOptions:
  - debug
{{ end -}}