{{- range .Values.rbd }}
apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: {{ .name }}
provisioner: rbd.csi.ceph.com
parameters:
  clusterID: {{ $.Values.auth.clusterId }}
  pool: {{ .pool }}
  imageFeatures: layering
  {{ template "secret" $ }}
reclaimPolicy: Delete
allowVolumeExpansion: true
mountOptions:
  - debug
---
{{ end -}}
